### ISSUE TITLE
[BUG] AutoMessage reload , resets existing config.yml and starts spamming chat

### ISSUE THREAD

**Issue by Tsoccerguy3** [poma123/AutoMessage#1]
Paper server build 625

/AutoMessage reload , resets our existing working config.yml and starts spamming chat with poma123 default message . From that point on , I can not not put any messages into the config.yml that will work . On every restart our servers config.yml gets replaced with the default config.yml and has only 1 line of text (# Delay in seconds )  and the chat spamming starts with Palma123 message that's built into plugin.

You need to provide more documentation ,
where is the source code ?
what page coding are you using ? UTF-8 , ANSI etc ... country character sets , etc ...
 better text parsing , because there is something or characters that the plugin doe not like , thus resetting the config.yml  on every restart .

Tested your plugin , measured and weighed , found it wanting . and deleted it

It may be that your plugin works for some people , just not for others and with no source or documentation i can only guess why .

**Comment by poma123** [comment]
I have no idea why this happened. Except you, no one wrote about such a bug.
Sorry for the inconvenience.

**Comment by Tsoccerguy3** [comment]
np , it was a ,   '    , character in the message that cause the config to reset to new default config file .

example that cause this , the word , " it's "  , some characters if not parsed need to be put in ""

**Comment by poma123** [comment]
Yeah, it's basic yaml knowledge.
